# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-us'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: thacklog
description: Thomas Hackl <br> Coding Biologist
cover: assets/images/blog-cover-kilauea.jpg
logo: assets/images/thackl-logo-blog.png
favicon: assets/images/favicon.png
production_url: https://thackl.github.io
source_url: https://github.com/thackl/thackl.github.io

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: th4ckl # replace by your username
facebook: False # replace by your username
github: thackl

# Disqus
disqus: False
disqus_shortname: thackl # replace with your disqus username

# Google Analytics
google_analytics: False # UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: thackl
branch: master
relative_source: ../
destination: _site/
production_url: https://thackl.github.io
source_url: https://github.com/thackl/thackl.github.io/

exclude:
  - blog-project.org
  - ideas
  - assets/css
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - LICENSE
  - "*.Rmd"
  - .git*
  - gulpfile.js
  - node_modules
  - package.json
