# -*- org-hierarchical-todo-statistics: nil; org-latex-with-hyperref: nil; org-export-allow-bind-keywords: t -*-
#+TITLE: Project 
#+AUTHOR: Thomas Hackl
#+DATE: 08/10/18

* Setting up my first blog
I want to start blogging using emacs orgmode and github. The most promising
route seems to be something like emacs-orgmode-publish + Jekyll (which powers github)

There are ton of tools, posts etc. out there

emacs org-mode  + github
https://orgmode.org/worg/org-blog-wiki.html -> https://orgmode.org/worg/org-tutorials/org-jekyll.html

** install ruby and jekyll

#+BEGIN_SRC sh
sudo apt -y install ruby ruby-dev build-essential
# set up local ~/ruby-gems folder in .path
gem install jekyll bundler jekyll-sitemap pygments.rb
#+END_SRC

** set up thackl.github.io

#+BEGIN_SRC sh
cd ~/projects/communicate/blog
git init
git create thackl.github.io

jekyll new --force . # otherwise complains about non-empty
jekyll serve # now it runs locally: http://localhost:4000/

sed -i '/_site/d' .gitignore # remove _site from .gitignore
git add *
git commit -am 'jekyll scaffold'
git push -u origin master # we're live: https://thackl.github.io/
#+END_SRC

** write posts in org-mode

Create a subdirectory for .org posts.

#+BEGIN_SRC sh
mkdir _org && cd _org
#+END_SRC

Add a minimal configuration for the org-mode publishing system to =~/.emacs=.

#+BEGIN_SRC elisp
(setq org-publish-project-alist
      '(("thackl.github.io" ;; my blog project
         ;; Path to org files.
         :base-directory "~/projects/communicate/blog/_org"
         :base-extension "org"
         ;; Path to Jekyll Posts
         :publishing-directory "~/projects/communicate/blog/_posts/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :html-extension "html"
         :body-only t
         )))
#+END_SRC

Write a publish a short post file:_org/2018-09-04-blogging-with-emacs-org-mode-and-jekyll.org.

The new post should be up on http://localhost:4000/ already.

** The Jasper2 theme

Actually a lot more work than I thought :)

https://github.com/jekyller/jasper2

#+BEGIN_SRC sh
mkdir ../blog-themes && cd ../blog-themes && git clone https://github.com/jekyller/jasper2
# copy over stuff we need
for FILE in assets _data _includes _layouts _plugins 404.html GHOST.txt Gemfile \
 LICENSE atom.xml index.html script.py _config.yml; do
  cp -r ../blog-themes/jasper2/$FILE .
done;

# update ruby gems to match ghost Gemfile requirements
bundle install

# NOW WE'RE LIVE
bundle exec jekyll serve
#+END_SRC

Got quite a bit to work - cover image, logo, ...

What doesn't work is the header nav bar on post pages - the elements seem to be
there, but only get visible when zooming in a lot. No idea what's going on there...

OK, seems to be an issue with my specific post - maybe the missing header image, ...

** Customizing the Site and Jasper2
*** DONE Site Cover on Post nav
    CLOSED: [2018-09-22 Sat 20:07]
I think some changes in post.html <div outer> or so

*** DONE Right-align Headline and Code Blocks
    CLOSED: [2018-09-22 Sat 20:07]
*** TODO preview code/figs in post feed instead of cover
- http://html2canvas.hertzen.com/
- post-card.html
*** DONE Contact: links to github, scholar, research gate, linked in email
    CLOSED: [2018-09-23 Sun 01:10]
*** DONE CV
    CLOSED: [2018-09-23 Sun 01:10]
*** TODO About me
Life stuff, fotos, etc
*** TODO Research
*** DONE Publications
    CLOSED: [2018-09-23 Sun 04:29]
[[file:_publication/google-scholar.R]]
